server:
  type: simple
  applicationContextPath: /
  adminContextPath: /admin
  minThreads: 100
  maxThreads: 100
  connector:
    port: 19000
    type: http

logging:
  level: INFO
  loggers:
      org.hibernate: ERROR
  appenders:
    - type: console
      threshold: ALL
      timeZone: UTC
      logFormat: "debugger %d [%thread] %-5level %c{15} - [%X{X-Transaction-Key} - %X{X-Request-Key}] - %msg%n%rEx"

fileConfig:
  filePath: ${FILE_PATH}
